/* ============================================================
   Paroliamo — contenuti dei giochi
   ============================================================ */
'use strict';

/* ---------- Nomi Cose Città: categorie base (on = attiva di default) ---------- */
const NCC_BASE = [
  { k: 'nome', t: 'Nome', on: 1 },
  { k: 'cosa', t: 'Cosa', on: 1 },
  { k: 'citta', t: 'Città', on: 1 },
  { k: 'animale', t: 'Animale', on: 1 },
  { k: 'cibo', t: 'Cibo o bevanda', on: 1 },
  { k: 'mestiere', t: 'Mestiere', on: 1 },
  { k: 'famoso', t: 'Personaggio famoso', on: 1 },
  { k: 'nazione', t: 'Nazione' },
  { k: 'film', t: 'Film o serie TV' },
  { k: 'marca', t: 'Marca' },
  { k: 'cantante', t: 'Cantante o band' },
  { k: 'sport', t: 'Sport o calciatore' },
  { k: 'fantasia', t: 'Personaggio di fantasia' },
  { k: 'corpo', t: 'Parte del corpo' },
  { k: 'colore', t: 'Colore' },
  { k: 'verbo', t: 'Verbo' },
  { k: 'casa', t: 'Oggetto di casa' },
  { k: 'geo', t: 'Fiume, lago o monte' },
  { k: 'insulto', t: 'Insulto (affettuoso)' },
  { k: 'scusa', t: 'Scusa per non uscire' },
  { k: 'regalo', t: 'Regalo pessimo' },
  { k: 'nascondiglio', t: 'Posto dove nascondersi' },
  { k: 'app', t: 'App o sito' },
  { k: 'malattia', t: 'Cosa che ti fa venire ansia' }
];
// lettere estraibili (niente straniere, niente H e Q che sono quasi impossibili)
const NCC_LETTERS = 'ABCDEFGILMNOPRSTUVZ';

/* ---------- Nominane 3 (si dice a voce) ---------- */
const TRE_CATS = [
  'squadre NBA', 'squadre di Serie A', 'marche di birra', 'Pokémon', 'personaggi dei Simpson', 'capitali europee',
  'cantanti di Sanremo', 'film di Harry Potter', 'supereroi Marvel', 'marche di automobili', 'gusti di gelato',
  'formati di pasta', 'formaggi', 'cocktail', 'videogiochi', 'serie Netflix', 'principesse Disney', 'cattivi Disney',
  'calciatori della Juventus', 'calciatori dell\'Inter', 'calciatori del Milan', 'piloti di Formula 1', 'tennisti',
  'stati americani', 'paesi africani', 'paesi dell\'Asia', 'isole italiane', 'regioni italiane', 'fiumi italiani',
  'città spagnole', 'città tedesche', 'pianeti', 'costellazioni o stelle', 'dinosauri', 'razze di cani', 'razze di gatti',
  'animali della savana', 'animali marini', 'uccelli', 'insetti', 'frutti tropicali', 'verdure verdi', 'spezie',
  'dolci italiani', 'piatti giapponesi', 'piatti messicani', 'catene di fast food', 'marche di merendine',
  'marche di vestiti', 'marche di scarpe', 'social network', 'app di messaggistica', 'marche di telefoni',
  'console di videogiochi', 'personaggi di Super Mario', 'personaggi di Star Wars', 'personaggi di Friends',
  'personaggi di Game of Thrones', 'personaggi dei Puffi', 'rapper italiani', 'rapper americani', 'band rock',
  'cantanti donne italiane', 'canzoni dei Måneskin', 'strumenti musicali', 'generi musicali', 'balli',
  'sport olimpici', 'sport con la palla', 'sport invernali', 'ruoli nel calcio', 'squadre di calcio inglesi',
  'squadre di calcio spagnole', 'vincitori del Pallone d\'Oro', 'attori italiani', 'attrici di Hollywood',
  'registi', 'film di Natale', 'film horror', 'cartoni animati giapponesi', 'cartoni degli anni 90',
  'personaggi dei Pokémon (non Pokémon)', 'youtuber o streamer italiani', 'programmi TV italiani',
  'conduttori TV', 'giochi da tavolo', 'giochi di carte', 'giochi da spiaggia', 'cose che porti in spiaggia',
  'cose che trovi in bagno', 'cose che trovi in frigo', 'cose che trovi in un ufficio', 'cose rosse', 'cose gialle',
  'cose rotonde', 'cose che pungono', 'cose che fanno rumore', 'cose che si rompono facilmente', 'cose che volano',
  'cose che puzzano', 'cose che si mangiano a colazione', 'ingredienti della pizza', 'condimenti per la pasta',
  'tipi di pane', 'bevande calde', 'superalcolici', 'vini italiani', 'mezzi di trasporto', 'parti di un\'auto',
  'parti del corpo sotto la vita', 'ossa del corpo', 'organi del corpo', 'malattie', 'mestieri in un ospedale',
  'lavori pericolosi', 'attrezzi da lavoro', 'utensili da cucina', 'elettrodomestici', 'mobili', 'tipi di scarpe',
  'capi d\'abbigliamento invernali', 'accessori', 'colori che non sono nell\'arcobaleno', 'forme geometriche',
  'materie scolastiche', 'cose che si fanno a scuola di nascosto', 'scuse per arrivare in ritardo',
  'cose che dice tua madre', 'parolacce in dialetto (gentili)', 'saluti in lingue straniere', 'lingue straniere',
  'monumenti famosi', 'musei', 'città con il mare', 'catene montuose', 'deserti', 'oceani o mari', 'vulcani',
  'santi', 'dei greci o romani', 'personaggi della Bibbia', 'imperatori romani', 'presidenti americani',
  'inventori o scienziati', 'pittori', 'scrittori italiani', 'libri famosi', 'fiabe', 'personaggi delle fiabe',
  'supercattivi dei film', 'robot famosi', 'alieni famosi', 'mostri leggendari', 'segni zodiacali', 'emoji',
  'cose che fai appena sveglio', 'posti dove fare un appuntamento', 'cose da fare a Capodanno', 'regali di Natale',
  'cose che compri all\'IKEA', 'marche di cioccolato', 'tipi di caramelle', 'gusti di patatine', 'frutti di bosco',
  'piante da appartamento', 'fiori', 'alberi', 'animali che vivono di notte', 'animali con le corna',
  'animali velenosi', 'animali della fattoria', 'versi di animali', 'cose che fanno i gatti'
];

/* ---------- Carte Scorrette: carte nere (___ = spazio da riempire) ---------- */
const CAH_BLACK = [
  'Il segreto di un matrimonio felice? ___.',
  'Mia nonna non esce mai di casa senza ___.',
  'Nuovo record su TikTok: 3 milioni di like per un video di ___.',
  'Cosa c\'è di sbagliato nella mia vita? ___.',
  'Il prof ha annullato il compito a causa di ___.',
  'Nel prossimo film Marvel, l\'eroe sconfigge il cattivo usando ___.',
  'Alla cena di Natale lo zio ha portato ___ e nessuno ha più parlato.',
  'Il mio terapeuta dice che tutti i miei problemi derivano da ___.',
  'Sono stato bannato dal gruppo WhatsApp del condominio per ___.',
  'La nuova app più scaricata d\'Italia: Tinder, ma per ___.',
  'Cosa mi tiene sveglio alle 3 di notte? ___.',
  'Il vero motivo per cui i dinosauri si sono estinti: ___.',
  'Benvenuti a MasterChef! Oggi cucineremo ___.',
  'Nel mio curriculum ho scritto che so fare ___.',
  'La prima cosa che farei se diventassi Presidente della Repubblica: ___.',
  'Cosa c\'è nella valigia di un influencer? ___.',
  'Sono le 2 di notte, il kebabbaro è chiuso, e io ho solo ___.',
  'La mia ex mi ha lasciato per ___.',
  'Cosa non bisogna mai portare a un primo appuntamento? ___.',
  'Se fossi un supereroe, il mio punto debole sarebbe ___.',
  '___: la causa numero uno dei litigi in famiglia.',
  'Il medico mi ha detto di smettere con ___.',
  'Il nuovo gusto della Nutella: ___.',
  'In fondo al mare, tra i relitti, hanno trovato ___.',
  'L\'ultimo desiderio del condannato: ___.',
  'Il tema di quest\'anno a Sanremo sarà ___.',
  'Ho provato a meditare ma continuavo a pensare a ___.',
  'Nel mio prossimo TED Talk parlerò di ___.',
  'Cosa ho trovato sotto il letto di mio fratello? ___.',
  'Le Olimpiadi aggiungono una nuova disciplina: ___.',
  'Cosa mi ha regalato la zia per il compleanno? ___.',
  'Il vero ingrediente segreto della carbonara: ___.',
  'Il mio gatto mi guarda come se sapesse di ___.',
  'Ho scritto una canzone d\'amore su ___.',
  'Nel prossimo Black Friday, sconti del 90% su ___.',
  'Babbo Natale quest\'anno porta solo ___.',
  'Alla gita scolastica è successo un casino per colpa di ___.',
  'Il prossimo reality show: dieci concorrenti chiusi in casa con ___.',
  'Cosa c\'è davvero nell\'Area 51? ___.',
  'Il motivo per cui non mi rispondono più ai messaggi: ___.',
  'Il mio talento nascosto è ___.',
  'Ho chiamato il mio primo figlio come ___.',
  'Stasera al telegiornale: «Italia sconvolta da ___».',
  'Dopo tre birre divento ___.',
  'Ricetta della felicità: un po\' di sole, un buon caffè e ___.',
  'Nel mio funerale voglio ___.',
  'Le mie vacanze ideali: spiaggia, mojito e ___.',
  'L\'inquilino del piano di sopra fa rumore ogni notte. Secondo me è ___.',
  'Signore e signori, il nuovo iPhone ha una funzione rivoluzionaria: ___.',
  'Il gruppo di calcetto si è sciolto per ___.',
  'Che cosa sognano le pecore elettriche? ___.',
  'Al colloquio di lavoro mi hanno chiesto della mia esperienza con ___.',
  '___ è il nuovo nero.',
  'Wikipedia ha appena aggiunto una pagina su ___.',
  'La mamma ha trovato la cronologia del mio browser: c\'era solo ___.',
  'In un mondo post-apocalittico, la nuova moneta sarà ___.',
  'Mi sono svegliato in una vasca piena di ghiaccio accanto a ___.',
  'Il cane dei vicini ha imparato a fare ___.',
  'Il prossimo libro di cucina: «100 ricette con ___».',
  'Durante la riunione su Zoom, il capo si è dimenticato la webcam accesa ed è apparso ___.',
  'La parola d\'ordine per entrare nella setta è ___.',
  'Unite ___ e ___ e otterrete il weekend perfetto.',
  '___ è meglio di ___. Fidati.',
  'Il nuovo film Pixar: la storia di ___ che si innamora di ___.',
  'Ho lasciato il lavoro per dedicarmi a ___ e ___.',
  'Il mio ultimo acquisto su Amazon: ___. Il mio rimpianto più grande: ___.',
  'Nella prossima stagione di Stranger Things, il Sottosopra è pieno di ___.',
  'Scienziati confermano: ___ allunga la vita.',
  'Mamma, papà, devo dirvi una cosa: ___.',
  'Per l\'esame di maturità ho portato una tesina su ___.',
  'Sui muri del bagno dell\'autogrill c\'era scritto ___.',
  'Il segreto della dieta mediterranea è ___.',
  'Dio ha creato il mondo in sei giorni. Il settimo ha inventato ___.',
  'Netflix ha cancellato la mia serie preferita per colpa di ___.',
  'Cosa porterei su un\'isola deserta? ___.',
  'La mia playlist per allenarmi contiene solo ___.',
  'La prossima moda dell\'estate: ___ al posto degli occhiali da sole.',
  'Cosa non dovrebbe mai dire un pilota d\'aereo? «Signori, abbiamo un problema con ___».',
  'L\'ingrediente che rovina qualsiasi festa: ___.',
  'La nuova religione si basa interamente su ___.'
];

/* ---------- Carte Scorrette: carte bianche ---------- */
const CAH_WHITE = [
  'Un piccione con troppa autostima', 'Lo zio che parla di politica a Natale', 'Una ciabatta lanciata con precisione militare',
  'Il gruppo WhatsApp dei genitori', 'Un vocale di 7 minuti', 'Mia nonna su Instagram', 'Un tatuaggio tribale fatto nel 2004',
  'La carbonara con la panna', 'Un procione che sa aprire il frigo', 'L\'ansia della domenica sera', 'Un ex che ti scrive alle 2 di notte',
  'Il commercialista', 'Una tisana drenante', 'Le crocs con i calzini', 'Un mutuo trentennale', 'Un influencer di crescita personale',
  'Un pinguino arrabbiato', 'La suocera', 'Un monopattino elettrico guidato male', 'La fila alle Poste', 'Un cugino che vende crypto',
  'Il wifi che non va', 'Una piadina alle tre di notte', 'Il sugo della domenica', 'Un karaoke stonato', 'Le zanzare di agosto',
  'Il latte scaduto', 'Una grigliata infinita', 'Un mago dei matrimoni', 'Il terrapiattismo', 'Un piede che puzza di formaggio',
  'Le pantofole della nonna', 'Un abbraccio non richiesto', 'Il segno della pace in chiesa', 'Una pizza con l\'ananas',
  'Un criceto depresso', 'Il prof di ginnastica', 'Le storie di Instagram del cane', 'Uno scontrino lunghissimo', 'Un tostapane assassino',
  'L\'ultima fetta di torta', 'Il vicino che trapana la domenica', 'La password dimenticata', 'Un selfie col cadavere di un piccione',
  'Il rutto più lungo d\'Italia', 'Un oroscopo inquietantemente preciso', 'Una dichiarazione d\'amore via SMS', 'Il gatto del vicino',
  'Un capitone vivo nella vasca', 'Una gita aziendale', 'Una startup che consegna acqua in bicicletta', 'Il tuo profilo LinkedIn',
  'Il bidet', 'Il pandoro contro il panettone', 'Un rave in parrocchia', 'Una sauna con sconosciuti', 'Un tacco 12 sui sampietrini',
  'La sagra della porchetta', 'Un unicorno con il mal di schiena', 'Una lasagna surgelata', 'Un sexy idraulico',
  'La mamma che ti chiama col nome intero', 'Un cane che giudica', 'Fare finta di essere al telefono', 'Una zia molto curiosa',
  'Il fantacalcio', 'Le scarpe bagnate', 'Una dieta a base di cracker', 'La ricevuta della pizza', 'Un tutorial di trucco fallito',
  'Un tatuaggio con un errore di ortografia', 'La sabbia nelle mutande', 'Un esorcismo fai da te', 'Un piatto di cozze sospette',
  'Il microonde che fa bip', 'Una caccia al tesoro aziendale', 'L\'uomo dei palloncini', 'Un alpaca in affitto',
  'La settimana bianca', 'Un tagliaerba con il motore truccato', 'Le palestre alle 7 di mattina', 'Un cono gelato caduto per terra',
  'La batteria all\'1%', 'Una piscina di Nutella', 'Un tronista', 'La lista della spesa di un serial killer',
  'Il nonno che guida', 'Un barbecue in balcone', 'Un frigorifero vuoto', 'Il mal di testa da sbornia', 'Un cinghiale a Roma',
  'Una sedia dell\'IKEA montata male', 'Il kebab delle quattro', 'Un\'anguria rubata', 'Il letto a castello', 'Il pigiama di Natale coordinato',
  'Un cane vestito da ape', 'Una riunione che poteva essere una mail', 'Un ragno nella doccia', 'Le chiavi chiuse in macchina',
  'Il Fantozzi che è in ognuno di noi', 'La seconda dose di tiramisù', 'Un abito da sposa noleggiato', 'Il cugino di campagna',
  'Il compleanno di un bambino di cinque anni', 'Le pulizie di primavera', 'Un messaggio vocale della nonna', 'Uno yogurt scaduto da un mese',
  'Un pappagallo che dice parolacce', 'Una lavatrice che balla', 'Il calendario dei pompieri', 'Una telenovela turca',
  'La nebbia in Val Padana', 'Un concerto di liscio', 'Un mojito annacquato', 'Una casa infestata ma in affitto a buon prezzo',
  'La ex del mio migliore amico', 'Il condizionatore rotto ad agosto', 'Una camicia hawaiana', 'Un calzino spaiato',
  'Un ex compagno di classe diventato ricchissimo', 'Uno spritz alle 11 di mattina', 'Il navigatore che ti porta in un campo',
  'Le briciole nel letto', 'Un video di gattini', 'Un trattore in tangenziale', 'Un ciuffo di peli inaspettato', 'Un costume ascellare',
  'Il parcheggiatore abusivo', 'Una pubblicità di 5 minuti su YouTube', 'Un furgone bianco sospetto', 'Il signore della mozzarella',
  'Un\'estate al mare con i genitori', 'Una lettera d\'amore piena di errori', 'Le caramelle della nonna sciolte in borsa', 'Un ventaglio',
  'La pasta scotta', 'Un influencer che piange in macchina', 'Il wrestling', 'Un elfo di Babbo Natale sindacalizzato',
  'Una partita a Monopoli finita in tragedia', 'Una pistola ad acqua carica di vino', 'Un gommone nel deserto', 'Un clown triste',
  'Un orsetto gommoso gigante', 'Le infradito a gennaio', 'Il cesso dell\'autogrill', 'La felpa dell\'ex', 'Un vicino nudista',
  'Il libretto delle istruzioni', 'Una carriera da tiktoker', 'Una crociera di dieci giorni', 'Il tuo oroscopo di oggi',
  'Una scatola di cioccolatini già mangiati', 'Il figlio del capo', 'Un pagliaccio a una festa di adulti', 'Le prove del coro',
  'Il gioco della bottiglia', 'Una tartaruga che corre', 'Un regalo riciclato', 'Le multe non pagate', 'Il dentista',
  'Una vecchia foto di classe', 'Un cucchiaio di olio di ricino', 'Il pollo crudo', 'Una macchina che fa un rumore strano',
  'Un tango appassionato col cameriere', 'La macchia di sugo sulla camicia bianca', 'Un brindisi imbarazzante', 'Un fidanzato immaginario',
  'Un divano che ha visto troppe cose', 'Un dito nel naso', 'L\'acqua frizzante', 'Il giorno del giudizio', 'Una motosega',
  'Un pinguino in smoking', 'Un panino con la mortadella', 'Una gara di sputi', 'Le tasse', 'Il karma', 'Un buco nero',
  'Un fantasma molto timido', 'Una sirena con le gambe', 'Il crollo del Wi-Fi durante la finale', 'Il ritorno dei Tamagotchi',
  'Un bacio con la lingua alla zia', 'Un nano da giardino rubato', 'Un ufficio senza aria condizionata', 'L\'ascensore bloccato',
  'Una pizza di 3 metri', 'Il bagnino', 'Una tuta acetata', 'Un toupé che vola via', 'Un ascesso', 'Un esame del sangue',
  'Le fake news di Facebook', 'Un complotto dei piccioni', 'Una mucca in ascensore', 'Il proprio riflesso alle 6 di mattina',
  'Una tazza con scritto «World\'s Best Boss»', 'Un cassetto pieno di cavi', 'La vicina che ti spia dalla finestra', 'Una cena di classe',
  'Il cane che mangia i compiti', 'La tazza del water alzata', 'Un sacchetto della spesa che si rompe', 'Il quarto d\'ora accademico',
  'Il torcicollo', 'Un capodanno in piazza', 'Il cenone di Natale avanzato a gennaio', 'Un\'ascella sudata', 'Un esploratore smarrito',
  'Un selfie stick', 'Una canzone di Gigi D\'Alessio', 'La Settimana Enigmistica', 'Un drone che ti segue', 'Una boyband anni 90',
  'Le sopracciglia disegnate col pennarello', 'Il primo giorno di dieta', 'Una partita a briscola truccata', 'Un\'ombrellone conteso',
  'Il nonno che racconta della guerra', 'Un lama che sputa', 'Un uovo di Pasqua senza sorpresa', 'Un capello nella minestra',
  'Il vino in cartone', 'Un portafoglio vuoto', 'Una relazione a distanza', 'Una zanzara tigre', 'L\'esame di guida',
  'Un balletto di gruppo a un matrimonio', 'Il papà che fa le battute', 'Il gelato al gusto puffo', 'Un pesce rosso immortale',
  'La sveglia che non suona', 'Un pigiama party di quarantenni', 'Un bancomat che si mangia la carta', 'La tazzina sbeccata',
  'Un piede sul tavolo', 'Uno sciopero dei treni', 'Il pranzo della domenica che dura sei ore', 'Una caramella alla liquirizia',
  'Un tuffo di pancia', 'Un fidanzato che fa CrossFit', 'Un gruppo di boy scout molto organizzati', 'Il fritto misto',
  'Una mail con scritto «come da accordi»', 'Un poeta da strada', 'Una nonna che fa i tortellini a mano', 'Un TikTok di ballo',
  'Un ombrello che si ribalta', 'Il vento in faccia in Vespa', 'Un vulcano attivo', 'Un vaso cinese del bisnonno',
  'La cronologia del browser', 'Un frigorifero che parla', 'Il cuggino che sa tutto', 'Un poster di Leonardo DiCaprio',
  'Le sardine in scatola', 'Un abbonamento in palestra mai usato', 'Uno shampoo al cocco', 'Una notte in tenda sotto la pioggia',
  'Il mago Otelma', 'La sindrome dell\'impostore', 'Un pugno sul tavolo', 'Un omino Lego sotto il piede', 'Un cartone di uova rotto',
  'La festa delle medie', 'Un barattolo che non si apre', 'Una spazzola piena di capelli', 'La coda in autostrada a Ferragosto',
  'Un alce in salotto', 'Un amico che non restituisce i soldi', 'Il compleanno del gatto', 'Un tamburello', 'Il guru dello yoga',
  'Una cabina armadio', 'Il mal di mare', 'Una fisarmonica', 'Un\'aragosta con un coltello', 'Un\'arancina contro un arancino',
  'Un panda che fa le capriole', 'Una vecchia Panda', 'Un cassonetto in fiamme', 'Un coniglio pasquale minaccioso',
  'Lo sguardo deluso di papà', 'Una bolletta della luce', 'Un tiramisù fatto col caffè della macchinetta', 'Un incontro con gli alieni',
  'Una mano che ti tocca il piede sotto il tavolo', 'Una lavastoviglie riempita male', 'Il sorriso finto delle foto di gruppo'
];
