/* ============================================================
   Paroliamo — domande per "Rarità"
   {p} viene sostituito col nome di un giocatore a caso della stanza.
   ============================================================ */
'use strict';

const QUESTIONS = [
  // --- categorie classiche (con risposte ovvie e risposte rare) ---
  'Un animale che non vorresti mai trovare nel letto',
  'Un frutto che sulla pizza sarebbe un crimine',
  'Un cantante italiano conosciuto con un nome solo',
  'Una città italiana che inizia con la B',
  'Un personaggio Disney cattivo',
  'Una marca di merendine',
  'Un ingrediente che non metteresti MAI nella carbonara',
  'Un animale che fa paura anche se è piccolo',
  'Un oggetto che trovi in qualsiasi cassetto della cucina',
  'Una parola che inizia con "ZA"',
  'Un formato di pasta',
  'Un gusto di gelato',
  'Uno sport che non hai mai visto giocare',
  'Una cosa gialla',
  'Un supereroe Marvel',
  'Una squadra di Serie A',
  'Un Paese dove non sei mai stato ma vorresti andare',
  'Un cartone animato degli anni 2000',
  'Un nome di cane',
  'Un piatto tipico regionale',
  'Un oggetto che si rompe sempre al momento sbagliato',
  'Una cosa che si trova in spiaggia',
  'Un videogioco famoso',
  'Una parola di 5 lettere che inizia con S',
  'Un animale con le strisce',
  'Un dolce italiano',
  'Una serie TV che hanno visto tutti',
  'Un personaggio dei Simpson',
  'Una cosa rotonda',
  'Un attore italiano',
  'Un mestiere che i bambini sognano di fare',
  'Un\'app che hai sul telefono',
  'Un insetto',
  'Un mezzo di trasporto',
  'Una bevanda',
  'Un colore che non è un colore dell\'arcobaleno',
  'Un capoluogo di regione',
  'Una cosa che si trova in bagno',
  'Un personaggio di Harry Potter',
  'Uno strumento musicale',
  'Un tipo di formaggio',
  'Una parola che fa rima con "cuore"',
  'Un pokemon',
  'Un personaggio storico',
  'Una catena di fast food',
  'Una parte del corpo che ha meno di 5 lettere',
  'Un fiume',
  'Un ortaggio',
  'Una marca di automobili',
  'Un pianeta o un corpo celeste',
  'Un influencer o youtuber italiano',
  'Un film di Natale',
  'Un uccello',
  'Un gioco da tavolo',
  'Una cosa che si fa in montagna',
  'Un piatto che si mangia con le mani',
  'Un calciatore leggendario',
  'Una lingua straniera',
  'Una cosa che si trova in un ufficio',
  'Una canzone che tutti conoscono a memoria',

  // --- situazioni assurde ---
  'Un superpotere completamente inutile',
  'Una scusa per non andare in palestra',
  'Una cosa che urleresti cadendo dalle scale',
  'Il posto peggiore per un primo appuntamento',
  'Una cosa da non dire mai al primo appuntamento',
  'Il nome di un pesce rosso',
  'Una cosa che porteresti su un\'isola deserta',
  'Un lavoro che non faresti nemmeno per un milione di euro',
  'Una cosa che fa tua nonna che ti fa impazzire',
  'Una frase tipica dei genitori italiani',
  'Una cosa che non bisognerebbe mai prestare',
  'Un motivo stupido per litigare in un gruppo WhatsApp',
  'Il peggior regalo di compleanno',
  'Una cosa che si fa alle 3 di notte',
  'Un oggetto che sarebbe un\'arma pessima in un film d\'azione',
  'Una cosa che non dovrebbe mai essere al gusto di fragola',
  'Una cosa che dici quando non hai capito cosa ti hanno detto',
  'Il nome peggiore per una nave da crociera',
  'Una cosa che ti fa venire ansia',
  'Qualcosa che si sente in un condominio',
  'Una cosa che si perde sempre',
  'Una cosa che compri all\'autogrill',
  'Una cosa che fa più paura dei ragni',
  'Un nome che daresti a una tartaruga',
  'Una cosa che non sai fare ma fingi di saper fare',
  'Una cosa che fanno solo i turisti',
  'Un\'emoji che usi troppo',
  'Una parola che fa ridere da dire',
  'Una cosa che si fa in fila alle Poste',
  'Una cosa che rovina un matrimonio',
  'Il peggior gusto di patatine possibile',
  'Una cosa che si dice al cameriere',
  'Una cosa che succede sempre in ogni film horror',
  'Un mestiere che sparirà fra 50 anni',
  'Il soprannome peggiore che si possa avere',
  'Una cosa che si trova nella borsa di una mamma',
  'Una cosa che un gatto butterebbe giù dal tavolo',
  'Il peggior nome per un ristorante',
  'Una cosa che ti chiede sempre il tuo vicino',
  'Una cosa che si sente dire in una riunione di lavoro',
  'Una cosa che fai quando nessuno ti guarda',
  'Una cosa che si mangia a Capodanno',
  'Un posto dove ti addormenteresti subito',
  'Una cosa che non entra mai in valigia',
  'Una cosa che si compra e non si usa mai',
  'Una cosa che si fa in treno',
  'Un animale che sarebbe un pessimo animale domestico',
  'Una cosa che dice il prof prima di un compito',
  'Un rumore fastidioso',
  'Una cosa che si fa durante una chiamata noiosa',
  'Una cosa che si trova sotto il divano',
  'Una cosa che ti fa sentire vecchio',
  'Un piatto che si brucia facilmente',
  'Una cosa che si urla allo stadio (senza parolacce)',
  'Il peggior nome per un supereroe',
  'Una cosa che non vorresti trovare nel panino',
  'Una cosa che fanno gli zii al pranzo di Natale',
  'Un oggetto che avresti voluto inventare tu',
  'Il titolo di un film sulla tua vita',
  'Una cosa che compreresti con 10 euro',
  'Una cosa che fai appena svegliato',
  'Una cosa che fa un influencer',
  'Il peggior posto dove rimanere bloccati',
  'Una cosa che si dice quando squilla il telefono e non vuoi rispondere',
  'Una moda che dovrebbe tornare',
  'Una moda che non deve tornare mai più',
  'Una cosa che si trova in un frigorifero di uno studente fuori sede',
  'Una cosa che ti fanno fare i genitori la domenica',
  'Una scusa per arrivare in ritardo',
  'Un tipo di persona che c\'è in ogni gruppo di amici',
  'Una cosa che non manca mai a una festa',
  'Una cosa che ti ruberebbe un procione',
  'Una cosa che faresti se fossi invisibile per un giorno',
  'Un animale che vincerebbe in una rissa contro un orso',
  'Il nome di un cocktail inventato',
  'Una cosa che si dice ai bambini per farli stare zitti',
  'Una cosa che si trova in un museo',
  'Una cosa che si sente in sala d\'attesa dal medico',
  'Il peggior lavoro estivo',
  'Una cosa che si fa per Halloween',
  'Una cosa che fa un gatto tutto il giorno',
  'Una parola inventata che dovrebbe esistere',
  'Una cosa che si compra all\'IKEA',
  'Una cosa che ti salverebbe in un\'apocalisse zombie',
  'Un difetto che tutti hanno',
  'Una cosa che dovrebbe essere vietata per legge',
  'Una cosa che si trova in macchina',
  'Una cosa che non si fa in ascensore',
  'Un pensiero che fai sotto la doccia',
  'Una cosa che mangeresti per il resto della vita',
  'Il peggior ingrediente per una torta',
  'Una cosa che si dice a un matrimonio',
  'Un\'abilità che si impara su YouTube',
  'Una cosa che si trova in un pronto soccorso',
  'Una cosa che si vince alle giostre',
  'Una cosa che si fa al mare quando piove',
  'Una cosa che dice l\'allenatore',
  'Una cosa che un alieno troverebbe strana di noi',
  'Il nome di una band inventata',
  'Una cosa che si nasconde ai genitori',
  'Una cosa che scrivi nella lista della spesa e dimentichi',

  // --- con i nomi degli amici ---
  'Cosa comprerebbe {p} con un milione di euro?',
  'Il lavoro perfetto per {p}',
  'Un animale che assomiglia a {p}',
  'Cosa ordina sempre {p} al ristorante?',
  'La canzone preferita di {p} sotto la doccia',
  'Il superpotere che avrebbe {p}',
  'Cosa porterebbe {p} su un\'isola deserta?',
  'Una cosa che {p} dice sempre',
  'Il nome del futuro cane di {p}',
  'Dove andrebbe in vacanza {p}?',
  'Il personaggio di un film che assomiglia di più a {p}',
  'Cosa fa {p} il sabato sera?',
  'La scusa preferita di {p} per arrivare in ritardo',
  'Cosa c\'è nel frigo di {p}?',
  'Il titolo dell\'autobiografia di {p}',
  'Lo sport in cui {p} sarebbe campione del mondo',
  'Cosa cerca {p} su Google alle 2 di notte?',
  'Il piatto che {p} cucina meglio (o peggio)',
  'Il primo acquisto di {p} se vincesse alla lotteria',
  'Il talent show che vincerebbe {p}',
  'La paura segreta di {p}',
  'L\'emoji che rappresenta meglio {p}',
  'Cosa farebbe {p} in un\'apocalisse zombie?',
  'Il nome d\'arte di {p} se fosse un rapper'
];
